version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: consumption_user
      POSTGRES_PASSWORD: consumption_pass
      POSTGRES_DB: consumption_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    environment:
      - DATABASE_URL=postgresql://consumption_user:consumption_pass@postgres/consumption_db
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  postgres_data: 